# Generated by Django 3.2.6 on 2021-08-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('url', models.TextField(blank=True)),
                ('publishedAt', models.TextField(blank=True)),
                ('sourceName', models.CharField(blank=True, max_length=100)),
                ('sentiment', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
