# Generated by Django 3.2.6 on 2021-08-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalArticles', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('url', models.URLField()),
                ('image', models.ImageField(upload_to='')),
                ('publishedAt', models.DateTimeField()),
                ('sourceName', models.CharField(max_length=100)),
                ('sentiment', models.CharField(max_length=50)),
            ],
        ),
    ]
