# Generated by Django 3.2.6 on 2021-08-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.RemoveField(
            model_name='article',
            name='totalArticles',
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='publishedAt',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='sentiment',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='sourceName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.TextField(blank=True),
        ),
    ]
