# Generated by Django 3.2.6 on 2021-08-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_category_historicalcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Historicalcategory',
        ),
        migrations.AlterField(
            model_name='article',
            name='sentiment',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='article',
            name='sourceName',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
