# Generated by Django 3.2.6 on 2021-08-29 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210826_2017'),
        ('articles', '0002_category'),
    ]

    operations = [
    ]
