# Generated by Django 3.2.6 on 2021-08-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.AlterField(
            model_name='article',
            name='publishedAt',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.TextField(blank=True),
        ),
    ]
