# Generated by Django 3.2.6 on 2021-08-30 19:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(blank=True, max_length=100)),
                ('volume', models.CharField(blank=True, max_length=100)),
                ('max_supply', models.CharField(blank=True, max_length=100)),
                ('price_change', models.CharField(blank=True, max_length=100)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
