# Generated by Django 3.2.6 on 2021-08-30 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coin',
            old_name='price_change',
            new_name='market_cap',
        ),
    ]
