# Generated by Django 3.2.6 on 2021-08-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_rename_price_change_coin_market_cap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='price',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
    ]
