# Generated by Django 3.2.6 on 2021-08-27 20:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article_watchlist',
            name='articles',
        ),
        migrations.RemoveField(
            model_name='article_watchlist',
            name='name',
        ),
        migrations.AddField(
            model_name='article_watchlist',
            name='author',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='article_watchlist',
            name='publishedAt',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='article_watchlist',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='article_watchlist',
            name='url',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='article_watchlist',
            name='urlToImage',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.RemoveField(
            model_name='article_watchlist',
            name='user',
        ),
        migrations.AddField(
            model_name='article_watchlist',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
