# Generated by Django 3.2.6 on 2021-08-27 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210827_2002'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock_watchlist',
        ),
    ]
