# Generated by Django 3.2.6 on 2021-08-22 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.TextField()),
                ('bid_price', models.IntegerField()),
                ('ask_price', models.IntegerField()),
                ('week_high_52', models.IntegerField()),
                ('week_low_52', models.IntegerField()),
                ('market_cap', models.IntegerField()),
                ('volume', models.IntegerField()),
            ],
        ),
    ]
