# Generated by Django 3.2.6 on 2021-08-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bidPrice', models.CharField(blank=True, max_length=100)),
                ('totalVolume', models.CharField(blank=True, max_length=100)),
                ('openPrice', models.CharField(blank=True, max_length=100)),
                ('closePrice', models.CharField(blank=True, max_length=100)),
                ('mark', models.CharField(blank=True, max_length=100)),
                ('volatility', models.CharField(blank=True, max_length=100)),
                ('peRatio', models.CharField(blank=True, max_length=100)),
                ('divAmount', models.CharField(blank=True, max_length=100)),
                ('divDate', models.CharField(blank=True, max_length=100)),
                ('markPercentChangeInDouble', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
